---
title: "Forecasting the Future Progress of Branch-And-Bound Search"
author: "Gregor Hendel, Pierre Le Bodic"
date: "15 April 2019"
output: html_document
params:
  full: false # run for all files or only a few
  path: './'
  minsize: 10
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE)
library(magrittr)
library(ggplot2)
library(dplyr)
library(forecast)

source("./functions.R")

if( ! dir.exists("plots") ) {
  print("Creating 'plots' directory")
  dir.create("plots")
}

errors <- read.csv("uniform_errors.csv")

probs <- errors$Prob %>% unique()

datafiles <- "../MMMc_v3/Data/uniform/%s.p_u.probs" %>% sprintf(probs)

```

## Visualization of Sample Trees

The following pictures show the actual search progress, the leaf frequency, and the number of unsolved nodes as a function of the number of leaves.
The curves in the second row depict the evolution of the estimation.


```{r uniform_arc_weights, echo=FALSE, results="asis"}

for (d in 1:ifelse(params$full, length(datafiles), 10))
{
  df <- probsFile2dataFrame(datafiles[d])
  errordf <- errors %>% subset(Prob == probs[d])
  if(nrow(df) < params$minsize)
    next
  # 
  cat("<h3>%s</h3>\n" %>% sprintf(probs[d] %>% as.character()))
  
  # knitr::kable(errordf %>% dplyr::select(EstimProg, EstimFreq, EstimUns, ErrorProg, ErrorFreq, ErrorUns, Actual, Current, Leaves, Level, Method)
               # , format = "html", booktabs=T) %>% kableExtra::kable_styling() %>% print() 
  
  simultaneousplot(df, errordf, title = probs[d], target = "print")
  
  # 
  # ggsave("plots/%s.png" %>% sprintf(progressPlotTitle(datafiles[d])))
}
```



